anguage: python

matrix:
  include:
    - python: 2.7
      env: NUMPY=1.9 SCIPY=0.15
    - python: 3.4
      env: NUMPY=1.9 SCIPY=0.15

before_install:
# - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda

install:
# - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
# - source activate test
 - conda install --yes numpy=$NUMPY scipy=$SCIPY matplotlib pip
 # Coverage packages are on my binstar channel
 - conda install --yes -c dan_blanchard python-coveralls
 - pip install setuptools
 - python setup.py install

script:
 - coverage run --source quantdsl -m discover unittest quantdsl

# Calculate coverage
after_success:
  - coveralls --config_file .coveragerc
